version: "3.8"

services:
  web:
    build: ./backend
    mem_limit: "1G"
    restart: "always"
    volumes:
      - ./backend/src:/app/src
      - ./frontend/build:/app/public
    ports:
      - "5000:5000"
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: "redis:alpine"
    restart: "always"
    volumes:
      - ./mounted-data/redis/data:/data
    mem_limit: "1G"
